INSERT INTO tb_user (ID, USER_NAME, PASSWORD, ROLE) VALUES(1, 'ray', 'ray', 'SUPER_USER');
INSERT INTO tb_user (ID, USER_NAME, PASSWORD, ROLE) VALUES(2, 'may', 'may', 'MANAGER');
INSERT INTO tb_user (ID, USER_NAME, PASSWORD, ROLE) VALUES(3, 'jay', 'jay', 'OPERATOR');
